name: Staging - deploy website

on:
  push:
    branches:
      - "dev"
    paths:
      - "web/**"

concurrency:
  group: web_deploy_staging

jobs:
  deploy:
    name: Deploy web (dev)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      
      - name: Set up node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn install

      # TODO: run tests
      # - name: Run tests
      #   run: ???

      - name: Build
        id: build
        run: CI=false && yarn run build   # CI=false means don't treat warnings as errors

      - name: Authenticate with Azure
        id: auth
        if: steps.build.outcome == 'success'
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'
          # Building credentials from separate parts: https://github.com/Azure/login#configure-a-service-principal-with-a-secret

      - name: Deploy
        if: steps.auth.outcome == 'success'
        uses: azure/webapps-deploy@v2
        with:
          app-name: ct-react-app10535090 # todo: should come from environment (ideally from Pulumi output)
          package: .next
