name: Staging - deploy website

on:
  push:
    branches:
      - "staging"
    paths:
      - "web/**"

concurrency:
  group: web_deploy_staging

jobs:
  deploy:
    name: Deploy web (dev)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.STAGING_DEPLOYER_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.STAGING_DEPLOYER_SECRET_ACCESS_KEY }}
      #     aws-region: ap-southeast-2
      
      - name: Set up node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn install

      # TODO: run tests
      # - name: Run tests
      #   run: ???

      - name: Build
        run: CI=false && yarn run build   # CI=false: don't treat warnings as errors

      # - name: Deploy
      #   if: success()
      #   run: aws s3 sync ./build s3://stage.groundschool.co.nz/ --acl public-read