name: Dev - deploy infra

on:
  pull_request:
    branches:
      - "dev"
    paths:
      - "iac/**"

jobs:
  up:
    name: Pulumi up (dev)
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Pulumi up
        uses: pulumi/actions@v4
        with:
          command: up
          stack-name: dev
          work-dir: iac
          cloud-url: ${{ secrets.PULUMI_STATE_BLOB_URL }}
        env:
          AZURE_STORAGE_ACCOUNT: ${{ secrets.PULUMI_STATE_STORAGE_ACCOUNT }}
          AZURE_STORAGE_KEY: ${{ secrets.PULUMI_STATE_STORAGE_ACCOUNT_KEY }}
          PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}

concurrency:
  group: iac_up_dev
