name: Staging - preview infra

on:
  pull_request:
    branches:
      - "staging"
    paths:
      - "iac/**"

jobs:
  preview:
    name: Pulumi preview (staging)
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - uses: pulumi/actions@v3
        with:
          command: preview
          stack-name: staging
          cloud-url: ${{ secrets.PULUMI_STATE_BLOB_URL }}
        env:
          AZURE_STORAGE_ACCOUNT: ${{ secrets.PULUMI_STATE_STORAGE_ACCOUNT }}
          AZURE_STORAGE_KEY: ${{ secrets.PULUMI_STATE_STORAGE_ACCOUNT_KEY }}
          AZURE_KEYVAULT_AUTH_VIA_CLI: true

concurrency:
  group: iac_preview_staging
